# Generated by Django 2.2.3 on 2020-04-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20200427_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于无法作为菜单的URL，可以为其选择一个可以作为菜单的权限，那么访问时，则默认选中此权限', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='rbac.Permission', verbose_name='默认选中权限'),
        ),
    ]
