# Generated by Django 2.2.3 on 2020-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='代码'),
        ),
    ]
